import { Poppins } from "next/font/google";
import { CartProvider } from "@/context/CartContext";
import { OrderProvider } from "@/context/OrderContext";
import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";
import Header from "@/components/layout/Header";
import { ProductProvider } from "@/context/ProductContext";
import Footer from "@/components/layout/Footer";
import { FavoriteProvider } from "@/context/FavoriteContext";
import { ModalProvider } from "@/context/ModalContext";
import ModalLayout from "@/layout/ModalLayout";
import { LayoutProvider } from "@/context/LayoutContext";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <AuthProvider>
          <ModalProvider>
            <ProductProvider>
              <CartProvider>
                <FavoriteProvider>
                  <OrderProvider>
                    <LayoutProvider>
                      <ModalLayout />
                      <Header />
                      <main>{children}</main>
                      <Footer />
                    </LayoutProvider>
                  </OrderProvider>
                </FavoriteProvider>
              </CartProvider>
            </ProductProvider>
          </ModalProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
